const fs = require('fs');

const codesFile = './product_codes_rich.json';
const data = JSON.parse(fs.readFileSync(codesFile, 'utf8'));

const bedroomMapping = {
    'pdf3/img-008': { code: '7603', name: 'Platform Bed' },
    'pdf3/img-011': { code: '7600Q-IVY', name: 'Platform Bed' },
    'pdf3/img-015': { code: '7602Q-GRAY', name: 'Platform Bed' },
    'pdf3/img-019': { code: '7602Q-IVY', name: 'Platform Bed' },
    'pdf3/img-025': { code: '7602-PINK', name: 'Platform Bed' },
    'pdf3/img-031': { code: '7401Q-BK', name: 'Platform Bed' },
    'pdf3/img-036': { code: '7402Q-WH', name: 'Platform Bed' },
    'pdf3/img-041': { code: '7405WH', name: 'Platform Bed' },
    'pdf3/img-050': { code: '7500-GRAY', name: 'Platform Bed' },
    'pdf3/img-056': { code: '7403GRAY', name: 'Platform Bed' },
    'pdf3/img-063': { code: '7404BK', name: 'Platform Bed' },
    'pdf3/img-072': { code: '7102 BROWN', name: 'Bed' },
    'pdf3/img-080': { code: '7102 GRAY', name: 'Bed' },
    'pdf3/img-085': { code: '7011GRAY', name: 'Bed' }
};

let count = 0;
for (const [image, item] of Object.entries(data)) {
    if (bedroomMapping[image]) {
        item.code = bedroomMapping[image].code;
        item.name = bedroomMapping[image].name;
        item.isAutoGenerated = false; // Mark as explicitly set
        count++;
    }
}

fs.writeFileSync(codesFile, JSON.stringify(data, null, 2));
console.log(`Updated ${count} bedroom products.`);
